export const enum AvailableCapabilities {
  Alarm = 'Alarm',
  BinarySensor = 'BinarySensor',
  Camera = 'Camera',
  ColorControl = 'ColorControl',
  DoorSensor = 'DoorSensor',
  EnergyMonitor = 'EnergyMonitor',
  LeakSensor = 'LeakSensor',
  Light = 'Light',
  Lock = 'Lock',
  MotionSensor = 'MotionSensor',
  MultiLevelSensor = 'MultiLevelSensor',
  MultiLevelSwitch = 'MultiLevelSwitch',
  OnOffSwitch = 'OnOffSwitch',
  PushButton = 'PushButton',
  SmartPlug = 'SmartPlug',
  TemperatureSensor = 'TemperatureSensor',
  Thermostat = 'Thermostat',
  VideoCamera = 'VideoCamera',
}

export const enum AvailableProperties {
  AlarmProperty = 'AlarmProperty',
  BooleanProperty = 'BooleanProperty',
  BrightnessProperty = 'BrightnessProperty',
  ColorProperty = 'ColorProperty',
  ColorTemperatureProperty = 'ColorTemperatureProperty',
  CurrentProperty = 'CurrentProperty',
  FrequencyProperty = 'FrequencyProperty',
  HeatingCoolingProperty = 'HeatingCoolingProperty',
  ImageProperty = 'ImageProperty',
  InstantaneousPowerProperty = 'InstantaneousPowerProperty',
  LeakProperty = 'LeakProperty',
  LevelProperty = 'LevelProperty',
  LockedProperty = 'LockedProperty',
  MotionProperty = 'MotionProperty',
  MultiLevelSwitch = 'MultiLevelSwitch',
  OnOffProperty = 'OnOffProperty',
  OpenProperty = 'OpenProperty',
  PushedProperty = 'PushedProperty',
  TargetTemperatureProperty = 'TargetTemperatureProperty',
  TemperatureProperty = 'TemperatureProperty',
  ThermostatModeProperty = 'ThermostatModeProperty',
  VideoProperty = 'VideoProperty',
  VoltageProperty = 'VoltageProperty',
}
